// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/IBM-Blockchain/fabric-deployer/deployer/components/ca"
	v1 "k8s.io/api/core/v1"
)

type Kube struct {
	GetConfigMapStub        func(string, string) (*v1.ConfigMap, error)
	getConfigMapMutex       sync.RWMutex
	getConfigMapArgsForCall []struct {
		arg1 string
		arg2 string
	}
	getConfigMapReturns struct {
		result1 *v1.ConfigMap
		result2 error
	}
	getConfigMapReturnsOnCall map[int]struct {
		result1 *v1.ConfigMap
		result2 error
	}
	GetPortStub        func(string, string) (int32, error)
	getPortMutex       sync.RWMutex
	getPortArgsForCall []struct {
		arg1 string
		arg2 string
	}
	getPortReturns struct {
		result1 int32
		result2 error
	}
	getPortReturnsOnCall map[int]struct {
		result1 int32
		result2 error
	}
	GetPortsStub        func(string, string) ([]v1.ServicePort, error)
	getPortsMutex       sync.RWMutex
	getPortsArgsForCall []struct {
		arg1 string
		arg2 string
	}
	getPortsReturns struct {
		result1 []v1.ServicePort
		result2 error
	}
	getPortsReturnsOnCall map[int]struct {
		result1 []v1.ServicePort
		result2 error
	}
	GetServiceStub        func(string, string) (*v1.Service, error)
	getServiceMutex       sync.RWMutex
	getServiceArgsForCall []struct {
		arg1 string
		arg2 string
	}
	getServiceReturns struct {
		result1 *v1.Service
		result2 error
	}
	getServiceReturnsOnCall map[int]struct {
		result1 *v1.Service
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Kube) GetConfigMap(arg1 string, arg2 string) (*v1.ConfigMap, error) {
	fake.getConfigMapMutex.Lock()
	ret, specificReturn := fake.getConfigMapReturnsOnCall[len(fake.getConfigMapArgsForCall)]
	fake.getConfigMapArgsForCall = append(fake.getConfigMapArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.GetConfigMapStub
	fakeReturns := fake.getConfigMapReturns
	fake.recordInvocation("GetConfigMap", []interface{}{arg1, arg2})
	fake.getConfigMapMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Kube) GetConfigMapCallCount() int {
	fake.getConfigMapMutex.RLock()
	defer fake.getConfigMapMutex.RUnlock()
	return len(fake.getConfigMapArgsForCall)
}

func (fake *Kube) GetConfigMapCalls(stub func(string, string) (*v1.ConfigMap, error)) {
	fake.getConfigMapMutex.Lock()
	defer fake.getConfigMapMutex.Unlock()
	fake.GetConfigMapStub = stub
}

func (fake *Kube) GetConfigMapArgsForCall(i int) (string, string) {
	fake.getConfigMapMutex.RLock()
	defer fake.getConfigMapMutex.RUnlock()
	argsForCall := fake.getConfigMapArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Kube) GetConfigMapReturns(result1 *v1.ConfigMap, result2 error) {
	fake.getConfigMapMutex.Lock()
	defer fake.getConfigMapMutex.Unlock()
	fake.GetConfigMapStub = nil
	fake.getConfigMapReturns = struct {
		result1 *v1.ConfigMap
		result2 error
	}{result1, result2}
}

func (fake *Kube) GetConfigMapReturnsOnCall(i int, result1 *v1.ConfigMap, result2 error) {
	fake.getConfigMapMutex.Lock()
	defer fake.getConfigMapMutex.Unlock()
	fake.GetConfigMapStub = nil
	if fake.getConfigMapReturnsOnCall == nil {
		fake.getConfigMapReturnsOnCall = make(map[int]struct {
			result1 *v1.ConfigMap
			result2 error
		})
	}
	fake.getConfigMapReturnsOnCall[i] = struct {
		result1 *v1.ConfigMap
		result2 error
	}{result1, result2}
}

func (fake *Kube) GetPort(arg1 string, arg2 string) (int32, error) {
	fake.getPortMutex.Lock()
	ret, specificReturn := fake.getPortReturnsOnCall[len(fake.getPortArgsForCall)]
	fake.getPortArgsForCall = append(fake.getPortArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.GetPortStub
	fakeReturns := fake.getPortReturns
	fake.recordInvocation("GetPort", []interface{}{arg1, arg2})
	fake.getPortMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Kube) GetPortCallCount() int {
	fake.getPortMutex.RLock()
	defer fake.getPortMutex.RUnlock()
	return len(fake.getPortArgsForCall)
}

func (fake *Kube) GetPortCalls(stub func(string, string) (int32, error)) {
	fake.getPortMutex.Lock()
	defer fake.getPortMutex.Unlock()
	fake.GetPortStub = stub
}

func (fake *Kube) GetPortArgsForCall(i int) (string, string) {
	fake.getPortMutex.RLock()
	defer fake.getPortMutex.RUnlock()
	argsForCall := fake.getPortArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Kube) GetPortReturns(result1 int32, result2 error) {
	fake.getPortMutex.Lock()
	defer fake.getPortMutex.Unlock()
	fake.GetPortStub = nil
	fake.getPortReturns = struct {
		result1 int32
		result2 error
	}{result1, result2}
}

func (fake *Kube) GetPortReturnsOnCall(i int, result1 int32, result2 error) {
	fake.getPortMutex.Lock()
	defer fake.getPortMutex.Unlock()
	fake.GetPortStub = nil
	if fake.getPortReturnsOnCall == nil {
		fake.getPortReturnsOnCall = make(map[int]struct {
			result1 int32
			result2 error
		})
	}
	fake.getPortReturnsOnCall[i] = struct {
		result1 int32
		result2 error
	}{result1, result2}
}

func (fake *Kube) GetPorts(arg1 string, arg2 string) ([]v1.ServicePort, error) {
	fake.getPortsMutex.Lock()
	ret, specificReturn := fake.getPortsReturnsOnCall[len(fake.getPortsArgsForCall)]
	fake.getPortsArgsForCall = append(fake.getPortsArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.GetPortsStub
	fakeReturns := fake.getPortsReturns
	fake.recordInvocation("GetPorts", []interface{}{arg1, arg2})
	fake.getPortsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Kube) GetPortsCallCount() int {
	fake.getPortsMutex.RLock()
	defer fake.getPortsMutex.RUnlock()
	return len(fake.getPortsArgsForCall)
}

func (fake *Kube) GetPortsCalls(stub func(string, string) ([]v1.ServicePort, error)) {
	fake.getPortsMutex.Lock()
	defer fake.getPortsMutex.Unlock()
	fake.GetPortsStub = stub
}

func (fake *Kube) GetPortsArgsForCall(i int) (string, string) {
	fake.getPortsMutex.RLock()
	defer fake.getPortsMutex.RUnlock()
	argsForCall := fake.getPortsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Kube) GetPortsReturns(result1 []v1.ServicePort, result2 error) {
	fake.getPortsMutex.Lock()
	defer fake.getPortsMutex.Unlock()
	fake.GetPortsStub = nil
	fake.getPortsReturns = struct {
		result1 []v1.ServicePort
		result2 error
	}{result1, result2}
}

func (fake *Kube) GetPortsReturnsOnCall(i int, result1 []v1.ServicePort, result2 error) {
	fake.getPortsMutex.Lock()
	defer fake.getPortsMutex.Unlock()
	fake.GetPortsStub = nil
	if fake.getPortsReturnsOnCall == nil {
		fake.getPortsReturnsOnCall = make(map[int]struct {
			result1 []v1.ServicePort
			result2 error
		})
	}
	fake.getPortsReturnsOnCall[i] = struct {
		result1 []v1.ServicePort
		result2 error
	}{result1, result2}
}

func (fake *Kube) GetService(arg1 string, arg2 string) (*v1.Service, error) {
	fake.getServiceMutex.Lock()
	ret, specificReturn := fake.getServiceReturnsOnCall[len(fake.getServiceArgsForCall)]
	fake.getServiceArgsForCall = append(fake.getServiceArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.GetServiceStub
	fakeReturns := fake.getServiceReturns
	fake.recordInvocation("GetService", []interface{}{arg1, arg2})
	fake.getServiceMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Kube) GetServiceCallCount() int {
	fake.getServiceMutex.RLock()
	defer fake.getServiceMutex.RUnlock()
	return len(fake.getServiceArgsForCall)
}

func (fake *Kube) GetServiceCalls(stub func(string, string) (*v1.Service, error)) {
	fake.getServiceMutex.Lock()
	defer fake.getServiceMutex.Unlock()
	fake.GetServiceStub = stub
}

func (fake *Kube) GetServiceArgsForCall(i int) (string, string) {
	fake.getServiceMutex.RLock()
	defer fake.getServiceMutex.RUnlock()
	argsForCall := fake.getServiceArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Kube) GetServiceReturns(result1 *v1.Service, result2 error) {
	fake.getServiceMutex.Lock()
	defer fake.getServiceMutex.Unlock()
	fake.GetServiceStub = nil
	fake.getServiceReturns = struct {
		result1 *v1.Service
		result2 error
	}{result1, result2}
}

func (fake *Kube) GetServiceReturnsOnCall(i int, result1 *v1.Service, result2 error) {
	fake.getServiceMutex.Lock()
	defer fake.getServiceMutex.Unlock()
	fake.GetServiceStub = nil
	if fake.getServiceReturnsOnCall == nil {
		fake.getServiceReturnsOnCall = make(map[int]struct {
			result1 *v1.Service
			result2 error
		})
	}
	fake.getServiceReturnsOnCall[i] = struct {
		result1 *v1.Service
		result2 error
	}{result1, result2}
}

func (fake *Kube) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getConfigMapMutex.RLock()
	defer fake.getConfigMapMutex.RUnlock()
	fake.getPortMutex.RLock()
	defer fake.getPortMutex.RUnlock()
	fake.getPortsMutex.RLock()
	defer fake.getPortsMutex.RUnlock()
	fake.getServiceMutex.RLock()
	defer fake.getServiceMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Kube) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ ca.Kube = new(Kube)
