name: Build Deployer image
on:
  pull_request:
    branches:
      - main

jobs:
  build-deployer-image:
    name: Build Deployer Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install curl build-essential -y
      - name: Checkout fabric-deployer repo
        uses: actions/checkout@v4
      - name: List repository files
        run: ls -la
      - name: Set up Make
        run: sudo apt-get install -y make
      - name: Build
        run: make image
      #- name: Push
       # env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #run: ./docker/publish_image.sh
