name: Build Deployer image
on:
  pull_request:
    branches:
      - main
env:
  GOPRIVATE: "github.com/IBM-Blockchain/*"
  GOPROXY: "https://proxy.golang.org,direct"
  GOPATH: /opt/go
  PATH: /opt/go/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
  GO_VER: 1.23.5

jobs:
  build-deployer-image:
    name: Build Deployer Image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/fabric-deployer
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/setup-go@v5
        name: Install Go
        with:
           go-version: ${{ env.GO_VER }}
      - name: Checkout fabric-deployer repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check Go version
        run: go version
      - name: List repository files
        run: ls -la
      - name: Build
        run: make image
      - name: Push
        run: make build-push
