name: Build Deployer image

on:
  pull_request:
    branches: [main]

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - name: Granting private modules access
        run: |
          git config --global url."https://${{ secrets.ACCESS_TOKEN }}:x-oauth-basic@github.com/IBM-Blockchain".insteadOf "https://github.com/IBM-Blockchain" 
      - name: Checkout fabric-deployer repo
        uses: actions/checkout@v3
      - name: Build
        run: make image
